server:
  port: ${PORT:8080}

spring:
  application:
    name: blog-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.blog: debug
